/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventana_pricipal;

// Importar mis clases
import clases.*;
import ventana_singup.SingUp;

// Importar librerias java
import javax.swing.Timer;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import jpanelimagen.ImagenFondo;

/**
 *
 * @author max98
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Window
     */
    public Principal() {
        initComponents();
        this.fncEstablecerItems();
        this.cmbox_anho.setSelectedIndex( this.cmbox_anho.getItemCount() - 19);
        this.setLocationRelativeTo(null);
        this.fncInsertarPicture(this.panel_1_Background, "/img/b2.jpg", false);
        
        panel_singup.setImagenFondo(new ImagenFondo( new java.io.File( getClass().getResource("/img/b2.jpg").getPath() ), 1.0f ));
        panel_registro.setImagenFondo(new ImagenFondo( new java.io.File( getClass().getResource("/img/b2.jpg").getPath() ), 1.0f ));
    }
    
    private void fncEstablecerItems(){
        this.cmbox_dia.removeAllItems();
        this.cmbox_mes.removeAllItems();
        this.cmbox_anho.removeAllItems();
        
        for(int item = 1; item <= 32; item++  ){
            if(item <= 9){
                this.cmbox_dia.addItem("0"+item);
            }else{
                this.cmbox_dia.addItem(""+item);
            }
        }
        
        for(int item = 1; item <= 12; item++  ){
            if(item <= 9){
                this.cmbox_mes.addItem("0"+item);
            }else{
                this.cmbox_mes.addItem(""+item);
            }
        }
        
        for(int item = 1985; item <= 2020; item++  ){
            this.cmbox_anho.addItem(""+item);
        }
        
    }
    
    
    private void fncInsertarPicture(JPanel contenedor, String url, boolean vaciar){
        
        if(vaciar) contenedor.removeAll();
        
        ImageIcon icono = new ImageIcon( getClass().getResource(url) );
        JLabel etiquetaImagen = new JLabel();
        etiquetaImagen.setBounds(0, 0, contenedor.getWidth(), contenedor.getHeight());
        etiquetaImagen.setIcon( new ImageIcon(icono.getImage().getScaledInstance(etiquetaImagen.getWidth(), etiquetaImagen.getHeight(), Image.SCALE_SMOOTH)) );
        contenedor.add(etiquetaImagen);
        
        if(vaciar) contenedor.validate();
        if(vaciar) contenedor.repaint();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_1_Background = new javax.swing.JPanel();
        btnRegistrarme = new javax.swing.JButton();
        btnIniciarSession = new javax.swing.JButton();
        panel_registro = new jpanelimagen.JPanelImagen();
        campo_nombres = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        campo_apellidos = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        campo_registro_email = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        campo_registro_contrasenha = new javax.swing.JPasswordField();
        cmbox_dia = new javax.swing.JComboBox<>();
        cmbox_mes = new javax.swing.JComboBox<>();
        cmbox_anho = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        sexo_femenino = new javax.swing.JRadioButton();
        sexo_masculino = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        panel_singup = new jpanelimagen.JPanelImagen();
        jLabel7 = new javax.swing.JLabel();
        campo_singup_email = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        campo_singup_contrasenha = new javax.swing.JPasswordField();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        btnRegistrarme.setBackground(new java.awt.Color(0, 102, 153));
        btnRegistrarme.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrarme.setText("Registrarme");
        btnRegistrarme.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnRegistrarmeMouseReleased(evt);
            }
        });

        btnIniciarSession.setBackground(new java.awt.Color(0, 153, 51));
        btnIniciarSession.setForeground(new java.awt.Color(255, 255, 255));
        btnIniciarSession.setText("Iniciar Session");
        btnIniciarSession.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnIniciarSessionMouseReleased(evt);
            }
        });

        panel_registro.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 2, true));
        panel_registro.setImagenFondo(new jpanelimagen.ImagenFondo(new java.io.File("C:/Program Files/NetBeans 8.2"),1.0f));

        campo_nombres.setText("jTextField1");

        jLabel1.setText("Nombre (s): ");

        jLabel2.setText("Apellidos: ");

        campo_apellidos.setText("jTextField1");

        jLabel3.setText("Nacimiento (DD/MM/AAAA):");

        jLabel4.setText("Contraseña:");

        campo_registro_email.setText("abc@quasar.org");

        jLabel5.setText("Email:");

        campo_registro_contrasenha.setText("jPasswordField1");

        cmbox_dia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        cmbox_mes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        cmbox_anho.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        jLabel6.setText("Sexo: ");

        sexo_femenino.setSelected(true);
        sexo_femenino.setText("Femenino");
        sexo_femenino.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                sexo_femeninoMouseReleased(evt);
            }
        });

        sexo_masculino.setText("Masculino");
        sexo_masculino.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                sexo_masculinoMouseReleased(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel9.setText("Formulario de registro");

        javax.swing.GroupLayout panel_registroLayout = new javax.swing.GroupLayout(panel_registro);
        panel_registro.setLayout(panel_registroLayout);
        panel_registroLayout.setHorizontalGroup(
            panel_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_registroLayout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(panel_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_registroLayout.createSequentialGroup()
                        .addGroup(panel_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(panel_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel5)
                                .addComponent(campo_registro_email)
                                .addGroup(panel_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(panel_registroLayout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(255, 255, 255))
                                    .addGroup(panel_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel1)
                                        .addComponent(campo_apellidos)
                                        .addComponent(campo_nombres, javax.swing.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE)))
                                .addComponent(campo_registro_contrasenha))
                            .addGroup(panel_registroLayout.createSequentialGroup()
                                .addGroup(panel_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panel_registroLayout.createSequentialGroup()
                                        .addComponent(cmbox_dia, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(cmbox_mes, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(sexo_femenino))
                                .addGap(18, 18, 18)
                                .addGroup(panel_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(sexo_masculino)
                                    .addComponent(cmbox_anho, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(23, 23, 23))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_registroLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(102, 102, 102))))
        );
        panel_registroLayout.setVerticalGroup(
            panel_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_registroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(campo_nombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campo_apellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbox_dia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbox_mes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbox_anho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sexo_femenino)
                    .addComponent(sexo_masculino))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(campo_registro_contrasenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campo_registro_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        panel_singup.setImagenFondo(new jpanelimagen.ImagenFondo(new java.io.File("C:/Program Files/NetBeans 8.2"),1.0f));

        jLabel7.setText("Contraseña: ");

        campo_singup_email.setText("jTextField1");

        jLabel8.setText("Email:");

        campo_singup_contrasenha.setText("jPasswordField1");

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel10.setText("Inicio de session");

        javax.swing.GroupLayout panel_singupLayout = new javax.swing.GroupLayout(panel_singup);
        panel_singup.setLayout(panel_singupLayout);
        panel_singupLayout.setHorizontalGroup(
            panel_singupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_singupLayout.createSequentialGroup()
                .addComponent(jLabel10)
                .addGap(0, 267, Short.MAX_VALUE))
            .addGroup(panel_singupLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_singupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(campo_singup_email)
                    .addComponent(campo_singup_contrasenha, javax.swing.GroupLayout.DEFAULT_SIZE, 362, Short.MAX_VALUE)
                    .addGroup(panel_singupLayout.createSequentialGroup()
                        .addGroup(panel_singupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panel_singupLayout.setVerticalGroup(
            panel_singupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_singupLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addGap(28, 28, 28)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(campo_singup_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campo_singup_contrasenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(280, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panel_1_BackgroundLayout = new javax.swing.GroupLayout(panel_1_Background);
        panel_1_Background.setLayout(panel_1_BackgroundLayout);
        panel_1_BackgroundLayout.setHorizontalGroup(
            panel_1_BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_1_BackgroundLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(panel_1_BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_1_BackgroundLayout.createSequentialGroup()
                        .addComponent(btnIniciarSession)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRegistrarme))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_1_BackgroundLayout.createSequentialGroup()
                        .addComponent(panel_singup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(panel_registro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21))
        );
        panel_1_BackgroundLayout.setVerticalGroup(
            panel_1_BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_1_BackgroundLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(panel_1_BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel_singup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel_registro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_1_BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnIniciarSession)
                    .addComponent(btnRegistrarme))
                .addGap(31, 31, 31))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_1_Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_1_Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarmeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarmeMouseReleased
        // TODO add your handling code here:
        int anho = Integer.parseInt( this.cmbox_anho.getItemAt( this.cmbox_anho.getSelectedIndex() ) );
        
        if( (2020-anho) < 18 ){
            JOptionPane.showMessageDialog(null, "Eres menor de edad!");
        }else if( this.campo_nombres.getText().isEmpty() ){
            JOptionPane.showMessageDialog(null, "Introduzca su(s) nombre(s), por favor...");
        }else if( this.campo_apellidos.getText().isEmpty() ){
            JOptionPane.showMessageDialog(null, "Introduzca su(s) apellido(s), por favor...");
        }else if( String.valueOf(this.campo_registro_contrasenha.getPassword()).isEmpty() ){
            JOptionPane.showMessageDialog(null, "Introduzca una contraseña, por favor...");
        }else if( this.campo_registro_email.getText().isEmpty() ){
            JOptionPane.showMessageDialog(null, "Introduzca un correo electronico, por favor...");
        }else if( !this.campo_registro_email.getText().contains("@quasar.org") || this.campo_registro_email.getText().length() < 14  ){
            JOptionPane.showMessageDialog(null, "Introduzca un correo electronico example@quasar.org, por favor...");
        }else{
            
            try {
                
                this.fncCrearCuentaNueva();
                String path = Storage.fncStorageObtenerRutaData(this.campo_registro_email.getText());
                
                File myObj = new File(path);
                
                // Registrar datos de usuario (.data)
                if (myObj.createNewFile()) {
                    FileWriter myWriter = new FileWriter(path);
                    
                    myWriter.write(this.campo_nombres.getText() + "\n");
                    myWriter.write(this.campo_apellidos.getText() + "\n");

                    String Fnacimiento = (String)this.cmbox_dia.getSelectedItem()+"/" + (String)this.cmbox_mes.getSelectedItem() +"/"+ (String)this.cmbox_anho.getSelectedItem();     
                    myWriter.write(Fnacimiento + "\n");

                    if( this.sexo_femenino.isSelected() ){
                        myWriter.write("Femenino" + "\n");
                    }else{
                        myWriter.write("Masculino" + "\n");
                    }

                    myWriter.write(String.valueOf(this.campo_singup_contrasenha.getPassword()) + "\n");
                    myWriter.write(this.campo_registro_email.getText() + "\n");
                    myWriter.write(Rutas.default_img + "\n");
                    
                    myWriter.close();
                                        
                    Storage.fncStorageAcoplarUnaLinea(Rutas.path_profiles, this.campo_registro_email.getText());
                    JOptionPane.showMessageDialog(null, "Usuario creado exitosamente...");
                    
                } else {
                    JOptionPane.showMessageDialog(null, "Usuario existente...\nIntroduzca un nuevo correo eletronico.");
                    Storage.fncStorageEliminarUnaLinea(new File(Rutas.path_profiles), this.campo_registro_email.getText());
                    myObj.delete();
                    
                }
                
            } catch (IOException e) {
                System.out.println("An error occurred.");
                e.printStackTrace();
            }
        }
        
    }//GEN-LAST:event_btnRegistrarmeMouseReleased

    private void sexo_femeninoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sexo_femeninoMouseReleased
        // TODO add your handling code here:
        this.sexo_femenino.setSelected(true);
        this.sexo_masculino.setSelected(false);
    }//GEN-LAST:event_sexo_femeninoMouseReleased

    private void sexo_masculinoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sexo_masculinoMouseReleased
        // TODO add your handling code here:
        this.sexo_femenino.setSelected(false);
        this.sexo_masculino.setSelected(true);
    }//GEN-LAST:event_sexo_masculinoMouseReleased

    private void btnIniciarSessionMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIniciarSessionMouseReleased
        // TODO add your handling code here:
        if( this.campo_singup_contrasenha.getText().isEmpty() ){
            JOptionPane.showMessageDialog(null, "Introduzca su contraseña, por favor...");
        }else if( this.campo_singup_email.getText().isEmpty() ){
            JOptionPane.showMessageDialog(null, "Introduzca su correo electronico, por favor...");
        }else{
            String _contenedor = Rutas.storage_profiles + this.campo_singup_email.getText();
            String _data = Storage.fncStorageObtenerRutaData(this.campo_singup_email.getText());
            
            File contenedor = new File(_contenedor);
            File file_data = new File(_data);
            
            // Verificar si existe el usuario
            if ( contenedor.isDirectory() && contenedor.exists() && file_data.exists() ) {
                
                // Verificar si la contraseña es correcta
                if( !fncVerificarContrasehna(_data) ){
                    JOptionPane.showMessageDialog(null, "Contraseña incorrecta... \n");
                }else{
                   // JOptionPane.showMessageDialog(null, "Iniciando session... \n");
                   
                   SingUp session = new SingUp( new Session( this.campo_singup_email.getText() ));
                   session.setVisible(true);
                   this.dispose();
                   session.fncMostrarMensajeDeBienvenida();
                   
                }
                
            } else {
                JOptionPane.showMessageDialog(null, "Usuario no existente...\nRegistre un nuevo usuario.");
            }
            
        }
    }//GEN-LAST:event_btnIniciarSessionMouseReleased
    
    private boolean fncVerificarContrasehna(String file){
        Scanner scanner;
        String tmpcontrasenha = "";
        try {
            scanner = new Scanner(new File(file));
            scanner.useDelimiter("\n");
                 
            int item = 0;
            while(scanner.hasNext()){
                String next = scanner.next();
  
                if( item == 4){
                    tmpcontrasenha = next;
                    break;
                } item++;
            }
                    
            scanner.close();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
                
        return String.valueOf(this.campo_singup_contrasenha.getPassword()).trim().equals( tmpcontrasenha );
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciarSession;
    private javax.swing.JButton btnRegistrarme;
    private javax.swing.JTextField campo_apellidos;
    private javax.swing.JTextField campo_nombres;
    private javax.swing.JPasswordField campo_registro_contrasenha;
    private javax.swing.JTextField campo_registro_email;
    private javax.swing.JPasswordField campo_singup_contrasenha;
    private javax.swing.JTextField campo_singup_email;
    private javax.swing.JComboBox<String> cmbox_anho;
    private javax.swing.JComboBox<String> cmbox_dia;
    private javax.swing.JComboBox<String> cmbox_mes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel panel_1_Background;
    private jpanelimagen.JPanelImagen panel_registro;
    private jpanelimagen.JPanelImagen panel_singup;
    private javax.swing.JRadioButton sexo_femenino;
    private javax.swing.JRadioButton sexo_masculino;
    // End of variables declaration//GEN-END:variables
    private ActionListener escucha;
    public Timer tiempo = new Timer(1000, escucha);

    private void fncCrearCuentaNueva() {
        new File( Rutas.storage_profiles + this.campo_registro_email.getText() ).mkdir();
        new File( Rutas.storage_profiles + this.campo_registro_email.getText() + Rutas.storage_profile ).mkdir();
        new File( Rutas.storage_profiles + this.campo_registro_email.getText() + Rutas.storage_chats).mkdir();
        try {
            new File( Rutas.storage_profiles + this.campo_registro_email.getText() + Rutas.storage_profile + this.campo_registro_email.getText() + Rutas.extesion_friends ).createNewFile();
            new File( Rutas.storage_profiles + this.campo_registro_email.getText() + Rutas.storage_profile + this.campo_registro_email.getText() + Rutas.extesion_chats ).createNewFile();
        } catch (IOException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
