/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paneles;

import clases.Rutas;
import clases.Session;
import clases.Storage;
import java.awt.Dimension;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author max98
 */
public class PanelFirma extends javax.swing.JPanel {

    /**
     * Creates new form JPanelFirma
     */
    public PanelFirma() {
        initComponents();
    }

    public PanelFirma(Session perfil) {
        initComponents();
        
        // * Establecer el tamaño para el panel
        this.setSize(470, 130);
        this.setPreferredSize(new Dimension(470, 130));

        // Establecer un tamaño al panel para la foto y agregar el imagen del correspondiente...
        this.panel_img_perfil.setSize(110, 130);
        String img_profile = Storage.fncStorageObtenerImgProfile(perfil);
        Storage.fncStorageInsertarPictureProfile(this.panel_img_perfil, img_profile, true);        
        
        // * Establecer el titulo para el panel
        this.txtf_titulo.setText( 
                perfil.getStrEmail() +" | "
              + perfil.getStrNombres() + " "
              + perfil.getStrApellidos() );
        this.txtf_titulo.setEditable(false);
        
        // * Establecer la firma para session activa
        this.txtarea_firma.setEditable(false);
        
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_img_perfil = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtarea_firma = new javax.swing.JTextArea();
        txtf_titulo = new javax.swing.JTextField();

        setBackground(new java.awt.Color(51, 51, 51));
        setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        panel_img_perfil.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panel_img_perfilLayout = new javax.swing.GroupLayout(panel_img_perfil);
        panel_img_perfil.setLayout(panel_img_perfilLayout);
        panel_img_perfilLayout.setHorizontalGroup(
            panel_img_perfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );
        panel_img_perfilLayout.setVerticalGroup(
            panel_img_perfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        txtarea_firma.setColumns(20);
        txtarea_firma.setRows(5);
        jScrollPane1.setViewportView(txtarea_firma);

        txtf_titulo.setBackground(new java.awt.Color(51, 51, 51));
        txtf_titulo.setForeground(new java.awt.Color(255, 255, 255));
        txtf_titulo.setText("Nombre e email");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel_img_perfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtf_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 56, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(txtf_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                .addGap(6, 6, 6))
            .addComponent(panel_img_perfil, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panel_img_perfil;
    private javax.swing.JTextArea txtarea_firma;
    private javax.swing.JTextField txtf_titulo;
    // End of variables declaration//GEN-END:variables
    private Session perfil;
    
    private void fncInsertarPicture(JPanel contenedor, String url, boolean vaciar){
        
        if(vaciar) contenedor.removeAll();
        
        System.out.println(url);
        ImageIcon icono = new ImageIcon( url );
        JLabel etiquetaImagen = new JLabel();
        etiquetaImagen.setBounds(0, 0, contenedor.getWidth(), contenedor.getHeight());
        etiquetaImagen.setIcon( new ImageIcon(icono.getImage().getScaledInstance(etiquetaImagen.getWidth(), etiquetaImagen.getHeight(), Image.SCALE_SMOOTH)) );
        contenedor.add(etiquetaImagen);
        
        if(vaciar) contenedor.validate();
        if(vaciar) contenedor.repaint();
    }
    
    public void setFirma(String firma){
        
        // * Verificar que la firma exista 
        if( !firma.isEmpty() )
            this.txtarea_firma.setText(firma);
        else
            this.txtarea_firma.setText("No disponible");

    }
    
}
